### ISSUE TITLE
TAA blackness with rapidly switching DoF focus plane

### ISSUE THREAD

**Issue by robertcupisz** [Unity-Technologies/PostProcessing#26]
Looks things going into focus cause TAA to go bonkers about its history buffer.

Repro: play the scene in the [project](https://www.dropbox.com/s/wifsd5eap5mny6z/DoFBlackFrameBug.zip?dl=1). Tested in 5.5b11 dx11.

[This is how it looks like when playing](https://demo.gyazo.com/20dc2541b24d79bc4fb52b6f86795a11)

[Still of the artifact](https://demo.gyazo.com/0e598d57b25a442a01d8f51889f920c6)

**Comment by robertcupisz** [comment]
Oops, looks like it's still there with a different aperture size.

Updated the [test project](https://www.dropbox.com/s/wifsd5eap5mny6z/DoFBlackFrameBug.zip?dl=1) to reflect it. Both the foreground sphere and the background alternate going black/grey. Includes the latest PP, tested in 5.5.0f3.

**Comment by Kink3d** [comment]
Fixed in @keijiro 's update. Will get a merge.

**Comment by robertcupisz** [comment]
![image](https://cloud.githubusercontent.com/assets/6276154/21890864/016f5940-d8d0-11e6-9222-ac9d0f1efe37.png)

The big black areas are gone indeed, but now, whenever the near sphere is in focus, it gets a low-res aliased outline (upsample filter issue? same problem as the latest update in https://github.com/Unity-Technologies/PostProcessing/issues/40?).

Also for some values of the focus distance, the outline becomes dark, like in the screenshot.

Updated project: https://www.dropbox.com/sh/ds7j7pi2e3nsqwn/AABiRgluuYl-534n3AgdxD-_a?dl=1

**Comment by robertcupisz** [comment]
I've tried out the latest DoF with CoC resampling from https://github.com/keijiro/PostProcessing/commit/db1c48ffb871a4e1e7361d10243b11c82e03f8b1

The dark halo is still there, CoC resampling making it even somewhat more pronounced as the edge of the object in focus is now sharper:

DoF disabled:
![a1](https://cloud.githubusercontent.com/assets/6276154/22426886/5e36110c-e701-11e6-9d33-60f9c35206b9.PNG)

DoF enabled, CoC resampling disabled:
![a2](https://cloud.githubusercontent.com/assets/6276154/22426904/733c751e-e701-11e6-8a69-4faffd5b59c3.PNG)

DoF enabled, CoC resampling enabled:
![a3](https://cloud.githubusercontent.com/assets/6276154/22426915/7ceccab4-e701-11e6-9f22-9f8b847f3ac7.PNG)

Updated project:
https://www.dropbox.com/s/vg2yodbvgzpghy0/DoFBlackFrameBug-v2.zip?dl=1

**Comment by robertcupisz** [comment]
Issue still there in the latest (https://github.com/Unity-Technologies/PostProcessing/commit/44b743140eeec5d10e7a9a6593269d6e8bc71fb4)
![a1](https://cloud.githubusercontent.com/assets/6276154/25388734/e818bafe-29ce-11e7-9d53-0a157c290c09.PNG)
![a2](https://cloud.githubusercontent.com/assets/6276154/25388740/ee840088-29ce-11e7-8ede-5b5ef0db3ad1.PNG)

**Comment by Kink3d** [comment]
Still reproduces in latest V2

**Comment by secondimpactrob** [comment]
Sorry to bump an old issue but this is still present and is quite frustrating. I'm seeing those dark edges described above around my in-focus geometry when using the depth of field effect. Particularly nasty when the subject is partially covered by transparent geometry, as the dark lines show through.

Would appear to be because in-focus geometry is black during downsample & blur stage, then when it is re-introduced the black has bled out into areas that are used by the final result.

Disabling the pre-multiply in DepthOfField.hlsl (line 141 at time of writing) the issue goes away. But with my extremely limited knowledge of these systems, I have no idea a) why this is pre-multiplied and b) what the ramifications would be for turning that off.

I guess this is a relatively minor issue for you guys, but would really appreciate your insight.

![dofDarkEdges](https://user-images.githubusercontent.com/39263943/61956148-71d0e380-afb4-11e9-9c4b-bff088ad06a0.PNG)
