### ISSUE TITLE
Depth of Field blur appears to be resolution-dependent

### ISSUE THREAD

**Issue by slime73** [Unity-Technologies/PostProcessing#29]
Maybe I'm doing something wrong or missing something obvious, but the Depth of Field seems to be noticeably different with the same settings depending on the game's resolution.

Here are two comparison screenshots of the effect used in the Unity standard assets example project, with the same DoF settings (as shown in the first pic) and different resolutions:

![dof1](https://cloud.githubusercontent.com/assets/2662/20863904/74c5fa80-b9b2-11e6-8b4b-e8668f057a01.PNG)

![dof2](https://cloud.githubusercontent.com/assets/2662/20863905/7827b696-b9b2-11e6-855b-2166749d42ef.PNG)

**Comment by Kink3d** [comment]
Hi, 

Thanks for the submission. The effect's resolution dependency is unfortunately intrinsic to the implementation. We are looking in to a solution to this.

**Comment by Kink3d** [comment]
Moved from #60 - Combining DoF questions

The Depth of field is not only dependent on the resolution, but also on the kernel size. I do understand that a smaller kernel will blur less if applied to the same image, but it would be possible to apply the blur on a downscaled image in order to create a similar effect. This would make sense in my eyes, because the only logical reason to choose a smaller kernel is to save performance. If you now want to use different quality settings, I would think that I just change the kernel size, but the effect stays pretty much the same. Right now with this implementation it is not possible to create a strong blur with a small kernel size.

Did you try to downsample the image, but were disappointed by the flickering result? If so, is there a possibility to look at that version. Or is this implementation bound to other thoughts I didn't grasp so far?

**Comment by Kink3d** [comment]
I have broadened the scope of this to include #60 as the issues are very much related.

**Comment by keijiro** [comment]
Hi @slime73 and @JohannesDeml,

Although the current implementation of the DoF was designed as resolution-independent, it has a few limitations.

- The maximum radius of CoC (circle of confusion) is limited by the kernel size.
- The effect of the DoF is weaken when the radius of CoC is nearly equal or smaller than twice of the pixel width.

The latter limitation comes from the fact that the current implementation uses a half-resolution buffer to process the source image.

The difference that can be observed in the screenshots from @slime73 comes from the latter limitation above. This kind of difference doesn't happen if the radius of CoC is large enough.

The problem suggested by @JohannesDeml mainly comes from the first limitation above. Although the workaround by him (pre-downscaling approach) could solve the problem partly, it has some drawbacks.

- It will introduce background bleeding (colors from focused objects bleed into defocused backgrounds).
- It can't process CoC smaller than the pixel width of the downscaled buffer. This is similar to the first limitation above; it'll be weaken more than the current implementation.

Thanks for the suggestions. We're always looking for a better solution for the resolution-dependency problem. Any suggestion is welcome!

**Comment by hippocoder** [comment]
If it will make the effect slower to introduce workarounds we should instead raise awareness of the issue, and make it trivial for people to create settings per resolution or aspect. I would guess that you would need to increase the resolution by 50% to see any perceptual differences anyway so it probably won't need many settings.

Alternatively scale the settings by a curve, user definable across resolutions, with a sensible default?

**Comment by SoloWingPixy2097** [comment]
Hi there,

First of, thanks for all the hard work put into this.

I've been struggling with this issue myself and there was no consistent way to adjust parameters upon changing resolution to maintain the same result, as such I dove into the code and noticed that sensor size is hard coded, which, yes, for "full frame", is correct, however, sensor size is directly related to Depth Of Field, cropped sensors creating a largerDOF  for the same focal length (since it is exactly that, a crop of the original DOF)
As a result, i exposed that parameter and played around with it to see if it correctly changed DOF upon resolution changes, my findings (as expected):

Doubling the resolution caused a narrower DOF (the "bug"), doubling the sensor size counteracted the narrowing of the DOF.
This was tested with multiple resolutions (all factors of 1080p, but the principle remains the same)

So to solve this issue, you can link sensor size to screen height, the only question is; which resolution height correlates with standard full frame format.

Hope this helps!

Kind Regards,
Alex

ps I rarely ever use GitHub, let alone explore other people's repositories, sry if this is not the way to do things

**Comment by Chman** [comment]
The sensor size is currently hard-coded because we don't have a concept of a "physical camera" at the moment in Unity. Exposing this raw setting to users would be very confusing so we choose to leave it there until we have a better camera solution in place (soon, hopefully).

**Comment by rsodre** [comment]
Excuses. We users don't care.
It's just frustrating, 6 months later we hear "soon, hopefully".
By that I understand nothing's being done.

**Comment by JohannesDeml** [comment]
@rsodre, this isn't helping at all. Please speak for yourself and not "we the users". Take a look at what they are doing on branch v2 (https://github.com/Unity-Technologies/PostProcessing/commits/v2) and you might think a bit different. Unity is working really hard to get everything right and I really appreciate that they build a solid foundation first. Nobody forces you to use the stack, if you want to get this feature resolved faster you can always do it yourself like @SoloWingPixy2097 did.
I'm also in the process of building my own stack, because it eats up too much performance on mobile and I need a scale-independent DoF, but I still highly appreciate the work done in this repo.

**Comment by rsodre** [comment]
Don't get me wrong, I really appreciate this stack and believe that Unity finally found it's way with it.
I just think that with Unity's expertise and after so many years, I shouldn't be struggling with their standard post solution, or having to dive into low level shader programming to fix it.
Didn't notice v2, will try it out, thanks.

**Comment by SoloWingPixy2097** [comment]
@Chman I see, thank you for the heads up ;-)

@rsodre The code is open source at the moment, so nothing stops you from customising Unity's implementation, they are offering it for free and it states that it is in beta, so snarky comments aren't going to advance anything.
You don't even have to fiddle around in shaders either, as sensor size (film size in Unity's code) is only being used for calculations prior sending data to shader.

**Comment by ryandeluz** [comment]
In case anyone needs explicit instructions (and really, please make this change and commit it to the next release!) open the DepthOfFieldComponent.cs, remove const from before k_FilmHeight, then have it update somewhere such as in Prepare, above CalculateFocalLength, add something like: k_FilmHeight = 0.024f * (Screen.height / 720.0f); 

720 can be changed to whatever number you want to use as your default screen height.

**Comment by iszlonn** [comment]
@ryandeluz I think I love you. Thank you very much.

**Comment by YourUncleBob** [comment]
I'd like to chime in a thanks as well. I didn't notice how much the DOF changed with resolution until we ran our game at full res on a 4K display. The DOF looked terrible at 4K. Faces that were in focus at 1080P completely blurred out and many of our shots just looked wrong.

This change fixed it and it is now looking close to identical at 1080P and 4K.

**Comment by juhaylimaki** [comment]
Downloaded the newest v2 but it looks like this issue still exists.
Anyone happen to have a version of this DepthOfFieldComponent.cs that has the resolution change fix?
Cheers!

**Comment by SethRobinson** [comment]
Update: It looks like the file was renamed to DepthOfField.cs.  ryandeluz's fix worked great on it though.

**Comment by Chman** [comment]
Hey,

Sorry it took so long to get to this one, we had to run a lot of tests and look into alternative solutions. I pushed a fix for the focus changing with screen size on the [dof-res-focus](https://github.com/Unity-Technologies/PostProcessing/tree/dof-res-focus) branch (it's basically the fix that @ryandeluz proposed earlier).

Let me know how it works for you.

**Comment by FireproofStudios** [comment]
I'm finding that even with the suggested fix (on the V1 branch), the Dof effect it still way stronger at higher resolutions. The dof-res-focus branch doesn't seem to exist any more, so I can test with that. 

Is anyone else finding the same? Is it fully fixed on the V2 branch (upgrading will be a big pain for us, so I don't want to go there without being fairly confident it's a fix)

Thanks!
Rob.

**Comment by Ricimon** [comment]
@FireproofStudios I did find the same issue, but after fiddling around with the math, this equation seemed to work pretty well for getting consistent DoFs at different screen sizes.
k_FilmHeight = 0.024f * Mathf.Pow(Screen.height / 1080.0f, -.75f);

**Comment by ziplock9000** [comment]
It still does not work. The effect is vastly different at different resolutions

**Comment by Ciro900** [comment]
I can confirm that the fix @ryandeluz posted does not work in version 2.0.17 (it did work fine on the old stack before V2). The DoF is much stronger at 1080P compared with 4K, making the new stack unusable for my exhibition which is viewed on multiple screens at different resolutions. Any other potential fixes to try?

**Comment by hippocoder** [comment]
I would suggest simply having a set of values for 1080p, and use an addition volume overriding only the DOF for 4k.

Then you can change the volume weight between 0 and 1.

**Comment by alternativevisual** [comment]
Lol, there is actually @ryandeluz's fix, and it's not working because of MaxCoCRadius.. but you can just add the same lines of code to the end result:
float screenResolution = (context.screenHeight / 720f);
float scaledFilmHeight = k_FilmHeight * screenResolution;
var coeff = f * f / (settings.aperture.value * (s1 - f) * scaledFilmHeight * 2f) * (screenResolution * 2);
var maxCoC = CalculateMaxCoCRadius(context.screenHeight) * (screenResolution * 2);
![image](https://user-images.githubusercontent.com/29812914/50082956-df4db200-0224-11e9-80d2-7e81cb8a64db.png)
and voila!
![image](https://user-images.githubusercontent.com/29812914/50083004-01473480-0225-11e9-8562-beb093f870f1.png)
![image](https://user-images.githubusercontent.com/29812914/50083008-060be880-0225-11e9-978e-ecb2abc9e4e6.png)
