### ISSUE TITLE
[V2] Temporal AA fails and leaves artifacts eventually covering the screen

### ISSUE THREAD

**Issue by gregharding** [Unity-Technologies/PostProcessing#337]
##### What happened?

I'm testing the V2 stack with hdr enabled (enabled on camera and in graphics settings) on MacOS/Metal and using TAA and Bloom. Often lighting effects cause TAA to fail and leave white holes/trails in the screen, eventually growing and covering everything. The artifacts can also be black depending on the settings of the bloom effect.

Disabling TAA or selecting another AA mode makes the artifacts immediately disappear. Re-enabling it makes the mess come back. Disabling bloom makes the artifact black instead of white. There is no change when using 'Stop NaN Propagation'.

Depending on the motion of gameobjects on screen, sometimes the artifacts can be reduced when something is moving through the affected regions. Some motion smears the artifacts more, other motion reduces it. So, the shape and growth of the artifacts appear directly linked to the motion vectors being rendered for use by the TAA.

Disabling hdr in the graphics settings (but leaving it enabled on the camera) allows the game to run without any problems.

##### Repro

I've managed to repro this in a basic scene (with TAA) by cranking a point light up to a very large intensity against a static plane and a moving cube using the default material. Eventually when the light intensity gets large enough (keep entering 9's until it breaks) the same artifacts appear, with the cube motion streaking artifacts across the game view. It might be related to NaN or out-of-range data from the light source.

Our game doesn't use any point lights with large intensities but a couple can be rendered over the top of each other at the same time which looks like it's causing out-of-range data that breaks things.

After further checks, it appears that using particles with the standard 'Particles/Alpha Blended' shader over the point light seems to break things easily, so perhaps the alpha blended particle shader and a bunch of overlapping particles is the cause. I tried modifying it eg. hardcoding output to fixed4(1,1,1,1) or fixed4(2,2,2,2) etc. and it doesn't break. We're not using fog and soft particles is not enabled in the quality settings, so there's only one relevant line in the fragment shader: fixed4 col = 2.0f * i.color * tex2D(_MainTex, i.texcoord). For our case, it looks like the point light and a bunch of overlapping alpha blended particles using that shader in the same place is the cause.

##### Post-processing stack version (v1, v2)?

v2 latest (2.0.0-b3, 2.0.0-b4).

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2017.2.0f3/p1/p2, MacOS 10.12.6 and Win 10, in the editor and standalone using MacOS or Windows desktop target. HDR enabled on cameras and graphics settings, using gamma colour space.

##### Screenshots

A game lighting effect and particle system was here for a moment, then white grows and takes over the entire screen eventually;
![image](https://user-images.githubusercontent.com/150406/31761814-c5dcda7e-b515-11e7-93f8-cd88603dd8b7.png)

Disabling the bloom but leaving TAA enabled makes the artifact black;
![image](https://user-images.githubusercontent.com/150406/31762020-6f9c62fa-b516-11e7-8113-0a49ecf8ddf4.png)

Disabling TAA removes the artifact completely;
![image](https://user-images.githubusercontent.com/150406/31762110-b3ca43b6-b516-11e7-9f97-a42533c4017c.png)

Eventual screen death...
![image](https://user-images.githubusercontent.com/150406/31762504-ea8da842-b517-11e7-8756-9db55b52a070.png)

Example of no bloom, TAA running with something moving across the screen and leaving a trail of garbage;
![image](https://user-images.githubusercontent.com/150406/31764420-9bc43504-b51d-11e7-8a9e-1a3be6e2083b.png)

Repro scene with plane, cube, and single point light at large intensity;
![image](https://user-images.githubusercontent.com/150406/31798913-47a8c680-b593-11e7-97bf-255a5484046a.png)

**Comment by artyom-zuev** [comment]
Encountered same issue on Unity 5.6.3p1 while running the editor on Windows 10 using PC project target. Had HDR enabled on cameras and in the graphics settings too, and was using linear color space. Hopefully this narrows down the possible sources of the issue. :)

**Comment by tatoforever** [comment]
I know how to fix all those problems. Change all your texture interpolators in your shaders to float and tadah, all your black and white pixels will dissapears. It's 99% of time data being badly interpolated (lack of precision). Try that in your small test case and you'll see.

**Comment by gregharding** [comment]
Thanks for the tip. I'll test some modified legacy particle shaders and see if that helps.

**Comment by gregharding** [comment]
@Chman can you reproduce this or would you like a repro project?

**Comment by tatoforever** [comment]
@gregharding 
Did you change the textures interpolators to floats? Make your entire shader use only floats and test like that.

**Comment by gregharding** [comment]
It's just the standard shipping 'Particles/Alpha Blended' shader. I think I modded it correctly to test various precisions. Only reducing the output power (adjusting a 2 * multiplier in there) stopped the blowing up from happening all the time.

**Comment by nicobella** [comment]
any solution to this? the black hole error propagation is happening in our project too, I'm using a custom amplify shader editor  shader, that is transparent an does refraction, nonetheless I use ASE for a lot of other shaders and the only one creating the NaNs or destroying the TAA is this one only, I can't figure out why, I have the Stop NaN Propagation option enabled but it doesn't help

**Comment by AubreyF** [comment]
Just wanted to add that I have been experiencing this issue in a project for the past six months, and that it impacts the V1 as well as the V2 stacks. I just upgraded my project to V2 in the hope that "Stop NaN Propagation" would mitigate the issue - but as Nicobella noted, this doesn't help. This occurs with a variety of different blended materials in every level of my game. It's debilitating enough that I have waited on shipping my alpha release 'till I can find a way to address it. I currently have an ingame button to toggle activation of the PostFX stack, because otherwise playtesting would be basically impossible.

**Comment by nicobella** [comment]
AubreyF if it helps in something, you can change TAA for SMAA or FXAA until TAA is fixed for good, just in case you need to ship your game now.

**Comment by AubreyF** [comment]
@nicobella Thanks for your suggestion. I am glad we brought this up, because I have some potentially new information to contribute. When I use SMAA or FXAA in my project, I still experience the black blobs popping into view. The difference is that only a single frame is impacted and they don't persist temporally.

My thought is that what we are seeing isn't an issue with broken shaders, TAA, or even AA in general. What we are seeing seems to be something broken deep in the PostFX stack.

**Comment by artyom-zuev** [comment]
@AubreyF 
For now I'd recommend using this workaround. Even though blended shaders still accumulate incorrectly under TAA with that fix, it at least eliminated all the black blobs for me.
https://github.com/Unity-Technologies/PostProcessing/issues/340#issuecomment-338378071

**Comment by AubreyF** [comment]
@artyom-zuev You, sir, are a gentleman and a scholar. Your (albeit temporary) TAA color maximalizer fix is working beautifully!

**Comment by tatoforever** [comment]
I had this same problem and was able to fix it using float interpolators instead of half. You can always try that, some people reported din't worked, it worked for me.

**Comment by gregharding** [comment]
We couldn't fix the problem by changing any shader precisions. In the meantime we're just disabling TAA and defaulting back to the other AA methods.

**Comment by artyom-zuev** [comment]
@Chman Is there any ETA for a fix to this? :)

**Comment by siponite** [comment]
Still no fix for this ? Please help @Chman , it's hard to go back to SMAA once you've tested TAA !

**Comment by fdmfdm** [comment]
had this issue as well, ended up clamping the final result before TAA would happen, which seems to have solved the issue for me :)

**Comment by siponite** [comment]
@fdmfdm Can you please tell us how you've done this ?

**Comment by fdmfdm** [comment]
@siponite  it is a somewhat ugly solution, as I needed to allow values above 1 (but anything above 3 could be turned down to 3 without visual change), so saturate did not do it for me, but In DeferredShading.shader:


	half3 ClampOutputcolor(half3 c)
	{
		return clamp(c, 0, 3);
	}

half4 CalculateLight(unity_v2f_deferred i)
	{
//do stuff
		res.rgb = ClampOutputcolor(res.rgb);
		return half4(res.rgb,0);
	}


the way I replicated the problem was by setting a mesh to a z scale of 0, this resulted in a lot of black flickering in the mesh, which im assuming is caused by invalid normals, which results in invalid lighting, which then results in an insanely high or low value, which when getting blended by TAA results in a black or white color (bloom would make it white on the edges and black in the center)

clamping it to a reasonable value would prevent the value from getting insanely high or low,

you could clamp it in the TemporalAntialiasing,shader in the Solve function, but that would require 3 clamps and im not 100% sure what results it would have with the several other postprocesses, so it seems safer to do it in the deferred shader and with pretty much the same cost (depending on how many light you have ofcourse)

**Comment by siponite** [comment]
Thanks a lot @fdmfdm !

**Comment by woistjadefox** [comment]
We definitely need a fix for this. I'm kinda worried to change anything in the DeferredShading.shader to get this working .. :-(

**Comment by TheRealCatherine** [comment]
Indeed I've run into this as well in issue #449 which I guess can be closed as a duplicate. Its worth noting my scene and lighting setup are very simple and what triggers it for me is setting a black skybox.

**Comment by Chman** [comment]
Latest commit (b40105b) should fix the `Stop NaN propagation` feature and properly kill NaNs before postfx. Note that this _won't_ fix the source issue (which is that you have NaNs in your framebuffer before post-processing is even applied).

**Comment by gregharding** [comment]
@Chman obviously NaN's in the framebuffer can cause problems, eg. in postprocessing, as we have found. I managed to repro the problem with tests using extreme lighting with a standard shader, and then again using just a standard (now legacy?) alpha blended particle shader.

If using basic Unity shaders or powerful lighting can cause them, are there any reasonable steps to detect or prevent them? Or, should we just switch on the NaN killer and be happy? :)

**Comment by Chman** [comment]
If the standard shader is outputting NaNs with extreme values I invite you to send an official bug report (as it's not post-processing related anymore) and in the meantime I'd keep the Stop NaN turned on :)

**Comment by gregharding** [comment]
@Chman thanks :)

I just tested the NaN patch and it doesn't work for us (on OSX). We still end up with black (no bloom) or white (using bloom) blobs appearing over the screen, eventually covering it depending on camera movement.

**Comment by woistjadefox** [comment]
@Chman hmm weird, we first thought that the bug disappeared, but one of our 5 employees still gets the black spreading. He definitely has the new NaN patch and cleared the library folder and anything that could hold a cached version. Can it somehow be related to specific hardware / GPU (even though I can't imagine such a scenario) ?

**Comment by Chman** [comment]
> We still end up with black (no bloom)

That's expected, NaNs will be turned to black pixels when they're found, we can't guess the expected pixel color. Although in this case it doesn't seem to work on Mac anyway (Metal or OpenGL?).

> Can it somehow be related to specific hardware / GPU (even though I can't imagine such a scenario) ?
Could be, that wouldn't be the first time we have issues with a GPU / driver combo... What hardware does it fail on? And what's the driver version?

This is suspicious though. Unless I get another valid repro-project it's going to be hard for me to help out. The most annoying part is that these NaNs rarely come from post-processing itself but from faulty object shaders or geometry...

**Comment by gregharding** [comment]
@Chman Tested OSX Metal (nVidia 650M) and Win10 DirectX 11 (GTX 1070) with 2017.2.1p3, both still have the problem - using TAA, black or white blobs (depending on bloom or no bloom) tear over the screen with camera movements. I'll see if I can make another repro project if you would like one.

**Comment by Chman** [comment]
> I'll see if I can make another repro project if you would like one.

Definitely, please do! I'm having a very hard time reproducing this, the only repro I got was because a skybox shader was outputting NaNs (which allowed to fix the NaN killer on our side) but yours sounds different.

**Comment by chrismarch** [comment]
We had this issue, and I don't believe we were inputting NaN to the TAA shader. We just had some larger HDR values, which seemed to quickly multiply to unsafe values within the TAA shader, in lines like:
`float4 corners = 4.0 * (topLeft + bottomRight) - 2.0 * color;`
`color += (color - (corners * 0.166667)) * 2.718282 * _Sharpness;`

The fix for us was to change:
`color = max(0.0, color);`
`// Tonemap color and history samples`
`float4 average = FastToneMap((corners + color) * 0.142857);`

to:
`color = max(0.0, color);`
**`color = min(color, HALF_MAX); // cmarch: make sure the HDR values are reasonable to avoid black splotches (probably from NaN out of the rcp in FastToneMap?)`**
`// Tonemap color and history samples`
`float4 average = FastToneMap((corners + color) * 0.142857);`

Thanks to @artyom-zuev for leading me in this direction (his exact fix did not work for us)

**Comment by artyom-zuev** [comment]
Thank for this, this looks like a better fix than my earlier attempt!

**Comment by woistjadefox** [comment]
@chrismarch thanks for the info / fix, but it didn't help in our case.

**Comment by chrismarch** [comment]
I've ended up putting more lines like color = min(color, HALF_MAX) after the black splotches happened again, although with much lower frequency reproduction. I've added these lines for all the colors that will go through FastToneMap (where I believe our NaNs were created from large values); after topLeft and bottomRight are assigned, as well as history, and I've changed HALF_MAX to 8, in an attempt to stop this completely.

**Comment by Chman** [comment]
Fixed in all my tests on 79350d3 (also fixes a bunch of other stuff, mostly for HDRP).

The NaN specific fixes in this commit are the clamp to `HALF_MAX_MINUS1`. On some machines values of `65504` would get rounded up to infinity when going through the ROP for whatever reason, so clamping to `HALF_MAX` isn't enough, you have to clamp to the previous representable fp16 value which is `65472.0` (`(2 - 2^-9) * 2^15`).

**Comment by gregharding** [comment]
Thanks, Thomas :) I will test this as soon as I can.

**Comment by gregharding** [comment]
I’ve tested Mac (MacBook Pro 2012, Nvidia GT 650M) and Win (Nvidia GTX 1070), both of which had TAA problems with legacy additive particle shaders and a few custom shaders - everything seems to be working well now. Thanks for the fix, Thomas :)

**Comment by artyom-zuev** [comment]
Same here, test scenes running on GTX1080 and GTX680 that previously had the issue no longer have it. Great work on this!
