### ISSUE TITLE
XR + TAA issue

### ISSUE THREAD

**Issue by robbiesri** [Unity-Technologies/PostProcessing#502]
Copy-pasta of @Anton-Tril report in another issue:
**************************
Hello there! Am I doing something wrong or TXAA still does not work in SinglePass for Windows builds? =) As for me TXAA is an uber important and absolutely must-have feature for any kind of VR and it will be extremely nice to have it with more efficient SinglePass. With multi-pass we need to find compromises between higher hardware requirements (which means cutting the number of customers) or more primitive graphics (which is also bad for marketing). This is a confusing situation because today making VR games is a pain - the market is young and tiny (2-5k sold copies is our maximum), and we need every customer to survive as small studio, so we can`t lose them because of super-noisy aliased image (MSAA or FXAA does not help) or because of asking to have expensive GeForce 1080Ti to get consistent 90 FPS. We are silently waiting for TXAA during last two years, seriously guys, now it is a good time to finally fix it =)

**Comment by robbiesri** [comment]
So...it should be working.  I recently tested TAA on Single-pass Doublewide on a 2018.1 build, and it seemed fine.

> because of super-noisy aliased image (MSAA or FXAA does not help)
So I understand _why_ devs gravitate toward TAA on XR, but I still don't think it's a good idea.  I think if you find that MSAA isn't helping you, I'd be curious about what the content is that you are trying to render. In my experience, many things that look good in monoscopic rendering don't really work in XR, and one of those things is trying to render items with finely detailed normal maps.  TAA works around the issue by smearing/blurring these fine details, but that's just a band-aid to work around content issues.

Anyway, what version are you testing this on?  XR TAA needs 2017.2+ because in earlier versions of Unity, it does not support jittered projection matrices for XR.  Without that, you can't have TAA.

**Comment by 01GOD** [comment]
@robbiesri So...after seeing "So...it should be working. I recently tested TAA on Single-pass Doublewide on a 2018.1 build, and it seemed fine." I had some hope and 30 minutes was stolen from Me while trying it again. 

I am using single pass stereo XR in 2017.3.1. Only the right viewport rendered scene. Left rendered blank gray. So...unless making an XR game with a pirate theme, only one viewport is not enough for XR. 

Try again. My previous comments have been confirmed more than before.

**Comment by Anton-Tril** [comment]
I am using 2017.3.1. As for content, indeed TAA produce a very blurry image but at least it reduces high-frequency aliasing noise. As for content - the simple reason is sci-fi scenes. MSAA works good but only on edges so it does not fix problems of specular aliasing, a flickering of cutout materials like grids.

**Comment by Podden** [comment]
cant get TAA to work on GearVR (S7 Edge, EU version, OpenGL ES3) either. 2018.1b10
Single Pass produces an image only on the right eye. In Multi Pass it seems to do nothing. Newest v2 commit, will try xr-texarray-infra branch next.

**Comment by robbiesri** [comment]
@Podden Nooo, it won't work!  I only got the base passthru case working for Stereo Instancing, not Multi-view (which is needed for Single-Pass Android). At the time, I couldn't tell if it was a bug with the Unity engine infrastructure or the device drivers.  I suspect drivers because...they break a lot. But I couldn't prove it at the time.

@Anton-Tril 
I totally hear you, but again...that typed of content (thin lines, high specular) is just not a good idea for VR (yet).  I realize that lots of people are using TAA to blur out these artifacts, but it's a band-aid.  In any case, it is what it is. Re: MSAA - I wonder if alpha-to-cutout would help with some of your issues...

In any case, the motion vector generation sounds like an issue.  Haven't had time to poke at this in a bit, not sure when I will :(  Hopefully next week...

**Comment by Podden** [comment]
thanks for the heads up.

**Comment by 01GOD** [comment]
robbiesri said: "I totally hear you, but again...that typed of content (thin lines, high specular) is just not a good idea for VR (yet). "

Sigh...copy/pastes to Unity HR department...

Can somebody contact Unity Europe and Unity Japan to have those locations get some people on this project???

For instance, Keijiro. Thanks in advance. Too many excuses here already...not necessarily saying that excessive excuses and delays are what happens when software engineering is outsourced to certain natiions, yet maaaaybe that is well known to happen.
