### ISSUE TITLE
ArgumentNullException: Argument can't be null.

### ISSUE THREAD

**Issue by jangofett890** [Unity-Technologies/PostProcessing#553]
I'm using the unity 2018 official release build and PostProcessing 2.0.5 in the package manager.

In just creating a new scene with a camera and a PostProcess Layer and Post Process Volume on the main camera with a blank render profile I get this error:

`ArgumentNullException: Argument cannot be null.
Parameter name: value
UnityEngine.MaterialPropertyBlock.SetTexture (Int32 name, UnityEngine.Texture value) (at C:/buildslave/unity/build/Runtime/Export/Shader.cs:159)
UnityEngine.Rendering.PostProcessing.Dithering.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at C:/Users/jango/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/Effects/Dithering.cs:31)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.RenderBuiltins (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context, Boolean isFinalPass, Int32 releaseTargetAfterUse) (at C:/Users/jango/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/PostProcessLayer.cs:857)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at C:/Users/jango/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/PostProcessLayer.cs:691)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at C:/Users/jango/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/PostProcessLayer.cs:437)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at C:/Users/jango/AppData/Local/Unity/cache/packages/packages.unity.com/com.unity.postprocessing@2.0.5-preview/PostProcessing/Runtime/PostProcessLayer.cs:294)
`

I've tried reinstalling the package and nothing is fixed.

**Comment by daschatten** [comment]
I have the same problem:

* blueNoise64 has 64 entries, but all are None
* blueNoise256 has 8 entries, all are None
* Auto Exposure is None

All others are filled

**Comment by rpopic2** [comment]
I had same issue, but I fixed it be re-installing it

**Comment by Chman** [comment]
This is an asset database & serialization issue in Unity. Sadly it's independent from the post-processing package (SRPs have the same random issue) so I can't "fix" it on my side. I've been tracking down this issue for a while now and it seems that in some cases the editor will change the resources asset GUID and thus break everything.

This has been reported and the editor team is working on a fix on their end, but I have no ETA for it :(

**Comment by Deadcows** [comment]
Is there a way of fixing it if I'm using Package Manager? As suggested I tried to reinstall package by removing AppData\Local\Unity\cache folder (which caused unity to reload packages I believe) but nothing changed, this issue is still appearing

**Comment by Kazkade** [comment]
Going to Assets > Reimport All fixed this issue for me.
