### ISSUE TITLE
Shift in the Image when Viewport Rect values are set

### ISSUE THREAD

**Issue by karthik7nike** [Unity-Technologies/PostProcessing#712]
When custom Viewport Rect. values are set on the Camera, the rendered image moves/shifts up with the Post-Process Layer.

In the following image, the viewport rect. values are set and the post-process layer is NOT applied.
![no post-process layer](https://user-images.githubusercontent.com/8691309/49145832-b3769500-f326-11e8-9a87-431010698596.JPG)

In the following image, the viewport rect. values are set and the post-process layer IS applied.
![post-process layer](https://user-images.githubusercontent.com/8691309/49145839-b83b4900-f326-11e8-8b22-f47eb896f15a.JPG)

Notice the shift.

Set-up:
Post-Process Layer and Volume (isGlobal = true) on Camera.
Viewport Rect. values = (X = 0, Y = 0.05, W = 1, H = 0.9)
No effects added, No AA, No Fog.
No change (with or without effects)

Post-Processing Version 2.1.0 (Imported from the Package Manager)
Unity 2018.2.7f1, Windows 7

**Comment by aliBUT** [comment]
I am facing the same issue in unity 2018.2.16

**Comment by spl0k** [comment]
This happens as soon as the camera's viewport position is not zero, whatever effects are enabled. You'll typically want this if you're doing some kind of split-screen (so #721 might be the same issue).

This is due to this line:
https://github.com/Unity-Technologies/PostProcessing/blob/bf46ec0c63f1581ca9e0917a95bac20ce7bc733b/PostProcessing/Runtime/PostProcessLayer.cs#L1145
And maybe this one too (but I haven't tested that case):
https://github.com/Unity-Technologies/PostProcessing/blob/bf46ec0c63f1581ca9e0917a95bac20ce7bc733b/PostProcessing/Runtime/PostProcessLayer.cs#L1231

Remove the last parameter (`context.camera.pixelRect`) from the call(s) and you should be good to go.

**Comment by iri0** [comment]
I had same issue with multi cameras and viewport rect.

The function BlitFullscreenTriangle in NOT work.
I traced these code then I found a workaround.
I only tested this code for my project Unity 2018.3.0f2.

RuntimeUtilities.cs
```
       public static void BlitFullscreenTriangle(this CommandBuffer cmd, RenderTargetIdentifier source, RenderTargetIdentifier destination, PropertySheet propertySheet, int pass, RenderBufferLoadAction loadAction, Rect? viewport = null)
        {
            cmd.SetGlobalTexture(ShaderIDs.MainTex, source);
            #if UNITY_2018_2_OR_NEWER
            bool clear = (loadAction == RenderBufferLoadAction.Clear);
            #else
            bool clear = false;
            #endif

	     /// this code is not work this time
            cmd.SetRenderTargetWithLoadStoreAction(destination, clear ? RenderBufferLoadAction.DontCare : loadAction, RenderBufferStoreAction.Store);

            if (viewport != null)
                cmd.SetViewport(viewport.Value);

            if (clear)
                cmd.ClearRenderTarget(true, true, Color.clear);

	     /// Add this function for SetRenderTarget
            cmd.SetRenderTarget(destination); 

            cmd.DrawMesh(fullscreenTriangle, Matrix4x4.identity, propertySheet.material, 0, pass, propertySheet.properties);
        }
```

**Comment by iri0** [comment]
I misundetstool the code......

comment out setviewport function like below.

RuntimeUtilities.cs
```
       public static void BlitFullscreenTriangle(this CommandBuffer cmd, RenderTargetIdentifier source, RenderTargetIdentifier destination, PropertySheet propertySheet, int pass, RenderBufferLoadAction loadAction, Rect? viewport = null)
        {
            cmd.SetGlobalTexture(ShaderIDs.MainTex, source);
            #if UNITY_2018_2_OR_NEWER
            bool clear = (loadAction == RenderBufferLoadAction.Clear);
            #else
            bool clear = false;
            #endif

            cmd.SetRenderTargetWithLoadStoreAction(destination, clear ? RenderBufferLoadAction.DontCare : loadAction, RenderBufferStoreAction.Store);

            //if (viewport != null)
            //    cmd.SetViewport(viewport.Value);

            if (clear)
                cmd.ClearRenderTarget(true, true, Color.clear);


            cmd.DrawMesh(fullscreenTriangle, Matrix4x4.identity, propertySheet.material, 0, pass, propertySheet.properties);
        }

```

**Comment by sttz** [comment]
We're using the camera's viewport rect to limit the aspect ratio and also see this image shift in Unity 2018.3.0f2. The fix from @spl0k above fixes the issue.

**Comment by GregFTW** [comment]
Same here. PostProcess + viewport rect offset for split screen. (effects for dramatization ;))
Unity 2018.3.0f2, standard rendering, packages up to date.
![image](https://user-images.githubusercontent.com/7061497/50922062-cf9f4300-1449-11e9-9d6d-61004a0fc6de.png)

After iri0 fix
![image](https://user-images.githubusercontent.com/7061497/50922551-193c5d80-144b-11e9-95c7-ab0b2641af26.png)

**Comment by iri0** [comment]
Today I tested Unity 2019.1.0a14.  this problem is fixed.
Of cource this is a alpha version...

I think, the problem is related to camera viewport problem in HDRP(2018.x.x).

**Comment by T5MattijsvanDelden** [comment]
> comment out setviewport function like below.

Great, that fixed our problem. Than you ! I was wondering why there was no longer any postprocessing at all in the second viewport in our splitscreen game (id DID work a while ago). But since the second player's camera rectangle is set to have an x coordinate of 0.5, the postprocessing rectangle was drawn offscreen...

**Comment by GitHubUser0803** [comment]
[iri0's fix](https://github.com/Unity-Technologies/PostProcessing/issues/712#issuecomment-452223993) confirmed working. Thanks.

**Comment by Gillissie** [comment]
I'm using 2018.4.6f1. I don't understand how to implement iri0's solution.

**Comment by iri0** [comment]
Hi Gillissie,
You open pps source code "RuntimeUtilities.cs" on your project,
and comment out two lines like explain above on my comment. 
But this problem is fixed after 2019.x so you consider to update your project if you can.   
Thanks

**Comment by Gillissie** [comment]
I'm sorry, but I don't know what pps source code is. Where exactly is this RuntimeUtilities.cs file located? How do I find it?
Thanks.

**Comment by iri0** [comment]
Go to this folder in your unity project.
\Library\PackageCache\com.unity.postprocessing@2.1.7\PostProcessing\Runtime\Utils

2.1.7 is pps version.

Thanks

**Comment by Gillissie** [comment]
Thank you. I guess "pps" stands for "post processing stack".

**Comment by MeatG** [comment]
This problem still persists. Could it be fixed?
I have a calculated 4:3 aspect viewport in my game regardless of player's real resolution/aspect and my own custom lens effect on the camera. Post processing engine crops the view because of this bug.

I can fix it with the above instructions, but it would be nice to have it fixed in the package, so I wouldn't have to manually get rid of the problem every time I update the packages...

I'm on Unity 2019.3, PPS 2.3.0 and URP 7.2.1

Thank you!

**Comment by iri0** [comment]
Today I tested Unity 2019.3.5.f1 and PPS 2.3.0 without SRP......
This problem still persists.

Unity 2019.3.5.f1 and HDRP 7.2.1 and PPS 2.3.0.......
This problem is fixed.
