### ISSUE TITLE
Can't build Android

### ISSUE THREAD

**Issue by antpaw** [Unity-Technologies/PostProcessing#726]
##### What happened?
i can not build for Android due to this error:
```
        Shader error in 'Hidden/PostProcessing/FinalPass': Input signature parameter SV_RenderTargetArrayIndex (1-based Entry 3) type must be a scalar uint. at line 42 (on gles)

        Compiling Vertex program with STEREO_INSTANCING_ENABLED
        Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING

        Error building Player: Shader error in 'Hidden/PostProcessing/FinalPass': Input signature parameter SV_RenderTargetArrayIndex (1-based Entry 3) type must be a scalar uint. at line 42 (on gles)

        Compiling Vertex program with STEREO_INSTANCING_ENABLED
        Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING
```

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2018.3.0f2, osx mojave, Android

**Comment by antpaw** [comment]
PP version 2.1.2

**Comment by mandarinx** [comment]
I get the same error when building for iOS. Same version of Unity and Post Processing package.

**Comment by ihgyug** [comment]
Same error on Android! Same version of Unity and post processing package.

**Comment by mandarinx** [comment]
I fixed it temporary by commenting out line 7: ```#pragma multi_compile __ STEREO_INSTANCING_ENABLED```

**Comment by antpaw** [comment]
@mandarinx thanks, but i can not access the source code because i've installed it via package manager

**Comment by mandarinx** [comment]
You can modify the source of any package by right clicking on a package in the project view, and click “Show in Finder”, or whatever appropriate for Windows. Any changes you makr will be overwritten by the next update of the package, so it’s not a permanent solution. Unless you copy the contents of the package source folder to your Assets folder. 

--
mandarin@mandarin.no
http://mandarin.no
+47 926 89 010

**Comment by itsOgden** [comment]
Have the same issue for iOS here. Unfortunately modifying the package locally doesn't fix the fact that it breaks in cloud build. Hopefully we can get a fix for this soon.

**Comment by j4hangir** [comment]
> I fixed it temporary by commenting out line 7: `#pragma multi_compile __ STEREO_INSTANCING_ENABLED`

Can we have this solution as a patch and get a release please.

**Comment by j4hangir** [comment]
HOW LONG IS THIS GONNA TAKE?

**Comment by UlfChristensen** [comment]
Issue and fix also applies to WebGL target. (Unity version 2018.3.2f1, using PostProcessing version 2.1.3)

**Comment by samizzo** [comment]
I stopped getting this with Unity 2018.3.6f1 and Post Processing package 2.1.3

**Comment by DmitriyYukhanov** [comment]
Still getting this with Unity 2018.3.6f1 and Post Processing 2.1.3 =D

**Comment by samizzo** [comment]
Weird! I'll have to look more carefully at my setup!

**Comment by azukizuki** [comment]
It seems to have been fixed in 2.1.4

**Comment by zoeesilcock** [comment]
Version 2.1.4 fixes this issue for me also,

**Comment by UlfChristensen** [comment]
WebGL problems also fixed in 2.1.4
